### ISSUE TITLE
Doesn't save all the changes

### ISSUE THREAD

**Issue by samuelba** [henrikingo/impressionist#20]
I open e.g. the `templates/official-demo` and move x/y around of a step. Then I press Ctrl+S to save it, however, the step jumps back to its original position.

It seems than only saving a rotation is working.

Is this supposed to work?

**Comment by henrikingo** [comment]
Can confirm. Thanks for reporting this.

My first suspicion is that this is related to rel plugin and impress().tear().

https://github.com/impress/impress.js/blob/628b78f3fd9829c66479c1b0bcf91ecfb2427742/src/plugins/rel/rel.js#L178

Since the official-demo doesn't use relative positioning, the above code should not do anything, but apparently it resets the coordinates in any event.

**Comment by henrikingo** [comment]
Thanks for reporting. This should be fixed now. Onto the next...
