### ISSUE TITLE
Embedded Image Selection

### ISSUE THREAD

**Issue by KeineLimonade** [henrikingo/impressionist#7]
When you want to add an image you may add a local one and select it via a menu (like the on for saving and opening​ files).

**Comment by henrikingo** [comment]
Hi

Did you notice that the TinyMCE toolbar has a button for adding an image element? Since no other TinyMCE functionality is available in a menu either, I'm of the opinion to not create a menu entry for images either.

The TinyMCE functionality currently is crude (e.g. no copy-paste, etc...) but can be extended with more advanced functionality.
